version: '3.8'

services:
  productcatalogue:
    build:
      context: .
      dockerfile: Dockerfile.productcatalogue  # Make sure this file exists
    ports:
      - "8020:8020"

  shopfront:
    build:
      context: .
      dockerfile: Dockerfile.shopfront  # Make sure this file exists
    ports:
      - "8010:8010"

  stockmanager:
    build:
      context: .
      dockerfile: Dockerfile.stockmanager  # Make sure this file exists
    ports:
      - "8030:8030"

